# Generated by Django 4.1.5 on 2023-02-09 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_aircraft_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completed', models.DateField()),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dep', models.CharField(max_length=4)),
                ('dest', models.CharField(max_length=4)),
                ('distance', models.IntegerField()),
                ('fuel', models.IntegerField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.aircraft')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='aircraft',
            name='items',
            field=models.ManyToManyField(to='main_app.item'),
        ),
    ]
