# Generated by Django 4.1.5 on 2023-02-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_item_feeding_aircraft_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeding',
            new_name='Flight',
        ),
    ]
