# Generated by Django 4.1.5 on 2023-02-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_feeding_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='fuel',
            new_name='fuel_rem',
        ),
        migrations.AddField(
            model_name='flight',
            name='fuel_used',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
