# Generated by Django 4.1.5 on 2023-02-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_fuel_flight_fuel_rem_flight_fuel_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='completed',
        ),
    ]
