# Generated by Django 4.1.5 on 2023-02-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complete',
        ),
    ]
